# Generated by Django 5.1.7 on 2025-04-18 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('father_or_spouse_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('personal_mobile', models.CharField(max_length=15)),
                ('personal_email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('official_mobile', models.CharField(max_length=15)),
                ('official_email', models.EmailField(max_length=254)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='employee_docs/aadhar/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='employee_docs/pan/')),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='employee_docs/salary/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='employee_docs/passport/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='employee_docs/driving/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='employee_docs/bank/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/offer/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_docs/photos/')),
                ('education_certificates', models.FileField(blank=True, null=True, upload_to='employee_docs/education/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/experience/')),
                ('relieving_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/relieving/')),
                ('appraisal_document', models.FileField(blank=True, null=True, upload_to='employee_docs/appraisal/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/medical/')),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/appointment/')),
                ('employee_agreement', models.FileField(blank=True, null=True, upload_to='employee_docs/agreement/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='employee_docs/insurance/')),
                ('tax_form', models.FileField(blank=True, null=True, upload_to='employee_docs/tax/')),
                ('nominee_form', models.FileField(blank=True, null=True, upload_to='employee_docs/nominee/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.bankaccount')),
                ('communication_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.communicationaddress')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.permanentaddress')),
            ],
        ),
    ]
