# Generated by Django 5.1.7 on 2025-04-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_id'),
    ]

    operations = [
    ]
