# Generated by Django 5.1.7 on 2025-03-31 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=10, unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('categories', models.CharField(choices=[('REG', 'Regular'), ('PRE_TRE', 'Premium & Trending'), ('PREM', 'Premium'), ('TREND', 'Trending')], default='REG', max_length=10)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Not Sold', 'Not Sold')], default='Not Sold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='number.pattern')),
            ],
        ),
    ]
