# Generated by Django 5.1.7 on 2025-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_remove_number_status_number_is_sold_number_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='circle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='current_operator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='dealer_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='dealer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='numberStatus',
            field=models.CharField(choices=[('RTP', 'RTP'), ('NONRTP', 'Non-RTP'), ('CODE_RTP', 'Code RTP'), ('PRE_TO_POST', 'Prepaid to Postpaid'), ('POST_TO_PRE', 'Postpaid to Prepaid')], default='RTP', max_length=20),
        ),
        migrations.AddField(
            model_name='number',
            name='parent_operator',
            field=models.CharField(choices=[('JIO', 'Jio'), ('AIRTEL', 'Airtel'), ('VI', 'Vi')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='number',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Hold', 'hold'), ('Sold', 'sold'), ('Sold By Vendor', 'sold by vendor'), ('Vendor Deactivated', 'vendor deactivated'), ('Pending Approval', 'pending approval')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='number',
            name='uploaded_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
