# Generated by Django 5.1.7 on 2025-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_number_circle_number_current_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='parent_operator',
            field=models.CharField(choices=[('JIO', 'jio'), ('AIRTEL', 'airtel'), ('VI', 'vi')], max_length=20, null=True),
        ),
    ]
