# Generated by Django 5.1.7 on 2025-04-11 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_alter_number_discount_alter_number_parent_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='number.pattern'),
        ),
    ]
