# Generated by Django 5.1.7 on 2025-04-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0005_alter_number_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='number.pattern'),
        ),
    ]
