# Generated by Django 5.1.7 on 2025-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0006_alter_number_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Hold', 'hold'), ('Sold', 'sold'), ('Sold by vendor', 'sold by vendor'), ('Vendor deactivated', 'vendor deactivated'), ('Pending approval', 'pending approval')], default='Available', max_length=20),
        ),
    ]
