# Generated by Django 5.2 on 2025-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0007_alter_number_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
