# Generated by Django 5.2 on 2025-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0008_number_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
