# Generated by Django 5.1.7 on 2025-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_aadhar_card_vendor_agreement_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='aadhar_card',
            field=models.FileField(default=None, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agreement_form',
            field=models.FileField(default=None, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_card',
            field=models.FileField(default=None, null=True, upload_to=None),
        ),
    ]
