# Generated by Django 5.1.7 on 2025-04-18 03:56

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='aadhar_card',
            field=models.FileField(blank=True, help_text='Upload Aadhar card document', max_length=255, null=True, upload_to=vendors.models.vendor_aadhar_upload_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='agreement_form',
            field=models.FileField(blank=True, help_text='Upload signed agreement form', max_length=255, null=True, upload_to=vendors.models.vendor_agreement_upload_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_card',
            field=models.FileField(blank=True, help_text='Upload PAN card document', max_length=255, null=True, upload_to=vendors.models.vendor_pan_upload_path),
        ),
    ]
