# Generated by Django 5.2 on 2025-04-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_aadhar_card_alter_vendor_agreement_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
