# Generated by Django 5.2 on 2025-05-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='metadata',
        ),
    ]
