# Generated by Django 5.1.7 on 2025-04-16 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('number', '0007_alter_number_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='customer.customer')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number.number')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'number')},
            },
        ),
    ]
