# Generated by Django 5.1.7 on 2025-04-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_remove_number_status_number_is_sold_number_vendor'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sales', to='number.number'),
        ),
    ]
