# Generated by Django 5.2 on 2025-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0010_number_approval_date'),
        ('sales', '0002_alter_sales_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='number',
        ),
        migrations.AddField(
            model_name='sales',
            name='numbers',
            field=models.ManyToManyField(related_name='number_sales', to='number.number'),
        ),
    ]
